<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Employee_Info [ <!ELEMENT Employee_Info (Employee)*>
<!ELEMENT Employee (Name, Department, Telephone, Email)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Department (#PCDATA)>
<!ELEMENT Telephone (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ATTLIST Employee Employee_Number CDATA #REQUIRED>
]>

<Employee_Info>
  <Employee  Employee_Number="105">
    <Name>Masashi Okamura</Name>
    <Department>Design Department</Department>
    <Telephone>03-1452-4567</Telephone>
    <Email>okamura@xmltr.co.jp</Email>
  </Employee>
  <Employee  Employee_Number="109">
    <Name>Aiko Tanaka</Name>
    <Department>Sales Department</Department>
    <Telephone>03-6459-98764</Telephone>
    <Email>tanaka@xmltr.co.jp</Email>
  </Employee>
</Employee_Info>